name: Build
on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"] # Ignore changes to markdown and workflow files

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
